"""New Migration 1.5

Revision ID: 6df020fd2a16
Revises: cf341e397fef
Create Date: 2025-04-13 12:44:30.462732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df020fd2a16'
down_revision: Union[str, None] = 'cf341e397fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('property', sa.Column('update_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('property', 'time_updated')
    op.drop_column('property', 'time_created')
    op.add_column('reservation', sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('reservation', sa.Column('update_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('reservation', 'time_updated')
    op.drop_column('reservation', 'time_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('reservation', 'update_date')
    op.drop_column('reservation', 'create_date')
    op.add_column('property', sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('property', 'update_date')
    op.drop_column('property', 'create_date')
    # ### end Alembic commands ###
