"""New Migration 1.2

Revision ID: 82d8bc11dd77
Revises: fbf3100e2e23
Create Date: 2025-04-11 11:33:40.925480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d8bc11dd77'
down_revision: Union[str, None] = 'fbf3100e2e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'capacity')
    # ### end Alembic commands ###
